### ISSUE TITLE
Issue: Possible incompatibility with latest GDAL 3.1.4 release

### ISSUE THREAD

**Issue by Saijin-Naib** [camptocamp/QGIS-SpreadSheetLayers#23]
My OSGeo4w just updated GDAL to 3.1.4, which seemingly has broken compatibility with SpreadSheet Layers.

![image](https://user-images.githubusercontent.com/19295950/96751468-3aa9d780-139b-11eb-95d9-e36edb49186c.png)

```
2020-10-21T12:38:56     CRITICAL    Traceback (most recent call last):
              File "D:/QGIS/apps/qgis/./python\qgis\utils.py", line 334, in _startPlugin
              plugins[packageName] = package.classFactory(iface)
              File "C:/Users/USERNAME/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\SpreadsheetLayers\__init__.py", line 34, in classFactory
              from .SpreadsheetLayersPlugin import SpreadsheetLayersPlugin
              File "D:/QGIS/apps/qgis/./python\qgis\utils.py", line 792, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              File "C:/Users/USERNAME/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\SpreadsheetLayers\SpreadsheetLayersPlugin.py", line 30, in 
              from .widgets.SpreadsheetLayersDialog import SpreadsheetLayersDialog
              File "D:/QGIS/apps/qgis/./python\qgis\utils.py", line 792, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              File "C:/Users/USERNAME/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\SpreadsheetLayers\widgets\SpreadsheetLayersDialog.py", line 35, in 
              from SpreadsheetLayers.util.gdal_util import GDAL_COMPAT
              File "D:/QGIS/apps/qgis/./python\qgis\utils.py", line 792, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              File "C:/Users/USERNAME/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\SpreadsheetLayers\util\gdal_util.py", line 45, in 
              GDAL_COMPAT = testGdal()
              File "C:/Users/USERNAME/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\SpreadsheetLayers\util\gdal_util.py", line 29, in testGdal
              lyr = ds.GetLayer(0)
             AttributeError: 'NoneType' object has no attribute 'GetLayer'
```

**Comment by arnaud-morvan** [comment]
I just tested with QGIS 3.22 / GDAL/OGR 3.3.2 and everything works file.
I close this old issue, feel free to reopen if needed.
