### ISSUE TITLE
importing ods-file leads to phyton runtime error

### ISSUE THREAD

**Issue by ThomasStruller** [camptocamp/QGIS-SpreadSheetLayers#49]
Opening an ods-file in Qgis 3.34 forced a phyton runtime error:

RuntimeError: Invalid value for number-rows-repeated = 1048565 May be caused by: Invalid value for number-rows-repeated = 1048560 
Traceback (most recent call last):
  File "C:\Users/thomas.struller/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\SpreadsheetLayers\widgets\SpreadsheetLayersDialog.py", line 324, in on_filePathButton_clicked
    self.afterOpenFile()
  File "C:\Users/thomas.struller/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\SpreadsheetLayers\widgets\SpreadsheetLayersDialog.py", line 329, in afterOpenFile
    self.openDataSource()
  File "C:\Users/thomas.struller/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\SpreadsheetLayers\widgets\SpreadsheetLayersDialog.py", line 362, in openDataSource
    if self.dataSource and self.dataSource.GetDriver().GetName() in ["XLS"]:
  File "C:\OSGeo4W\apps\Python39\lib\site-packages\osgeo\ogr.py", line 1287, in __len__
    return self.GetLayerCount()
  File "C:\OSGeo4W\apps\Python39\lib\site-packages\osgeo\ogr.py", line 838, in GetLayerCount
    return _ogr.DataSource_GetLayerCount(self, *args)
RuntimeError: Invalid value for number-rows-repeated = 1048565
May be caused by: Invalid value for number-rows-repeated = 1048560

Python-Version: 3.9.18 (heads/master:5eba59e, Feb  1 2024, 20:02:10) [MSC v.1929 64 bit (AMD64)] 
QGIS-Version: 3.34.4-Prizren Prizren, decd43dc 

Python-Pfad:
C:\Users/thomas.struller/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\ThToolBox
C:\Users/thomas.struller/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\ProcessX
C:\Users/thomas.struller/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\postgis_toolbox
C:\Users/thomas.struller/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\pdaltools
C:\Users/thomas.struller/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\munsellrgb
C:\Users/thomas.struller/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\contour
C:/OSGeo4W/apps/qgis-ltr/./python
C:/Users/thomas.struller/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/thomas.struller/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/OSGeo4W/apps/qgis-ltr/./python/plugins
C:\OSGeo4W\apps\grass\grass83\etc\python
C:\Users\thomas.struller\Documents
C:\OSGeo4W\bin\python39.zip
C:\OSGeo4W\apps\Python39\DLLs
C:\OSGeo4W\apps\Python39\lib
C:\OSGeo4W\bin
C:\OSGeo4W\apps\Python39
C:\OSGeo4W\apps\Python39\lib\site-packages
C:\OSGeo4W\apps\Python39\lib\site-packages\win32
C:\OSGeo4W\apps\Python39\lib\site-packages\win32\lib
C:\OSGeo4W\apps\Python39\lib\site-packages\Pythonwin
C:/Users/thomas.struller/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:\Users\thomas.struller\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\DigitizingTools\tools
C:\Users\thomas.struller\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\DigitizingTools
C:\Users/thomas.struller/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis_resource_sharing
C:\Users\thomas.struller\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\qgis_resource_sharing
C:\Users\thomas.struller\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\qgis_resource_sharing\ext_libs
C:\Users\thomas.struller\AppData\Roaming\QGIS\QGIS3\profiles\default\python\site-packages
W:/Guggenmuehle

**Comment by arnaud-morvan** [comment]
Hello @ThomasStruller ,

Thanks for raising this.

Can you provide an example file so I can try to reproduce ?

The error seems to happen in OGR, I suspect that OGR did not managed to read your file, in which case I would not be able to fix it. This plugin is just a dialog to create an OGR VRT file.

If you cannot open your file directly in QGIS using OGR provider, the issue might not be fixable on the SpreadSheetLayers plugin side.

Regards

**Comment by Nnoemie** [comment]
Hello, I am getting, I think, the same kind of issue trying to import a heavy .ids fil with more than 30 sheets : 

> RuntimeError: Too much accumulated memory for row/cell repetition. Parsing stopped May be caused by: Formula Parsing Error: syntax error (...) File "C:\PROGRA~1\QGIS 3.40.8\apps\Python312\Lib\site-packages\osgeo\gdal.py", line 5498, in GetLayerCount
    return _gdal.Dataset_GetLayerCount(self, *args)

Is there a way to allow more sheets to be ridden? Note that when using the standard "add a vector layer" item in Qgis : I can only select one or the first 30 sheets.
